-- Semi-Presidential Government Type: Phase 1 Foundation
-- Adds 'Semi-Presidential' as a valid government_type for nations.
-- Semi-Presidential nations have BOTH an elected president AND a parliamentary PM.
--
-- No schema changes needed — government_type is an unconstrained TEXT column.
-- This migration serves as documentation and ensures the administrations table
-- also recognises the new type in any future queries.
--
-- Valid government_type values are now:
--   'Democracy'          (Parliamentary Democracy / Constitutional Monarchy)
--   'Presidential'       (Presidential Republic)
--   'Semi-Presidential'  (Semi-Presidential Republic)
--
-- To convert an existing nation to Semi-Presidential (example):
--   UPDATE nations SET government_type = 'Semi-Presidential' WHERE id = '<nation_id>';
--
-- The tick processor and all client code now handle 'Semi-Presidential' via
-- capability helpers: hasElectedPresident() and hasParliamentaryPM().
