-- Corporation contracts system.
-- Contracts are generated by governments (infrastructure spending) or private corps (property needs).
-- Construction corporations bid on contracts; the issuer selects the winner.

CREATE TABLE IF NOT EXISTS corp_contracts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Contract identity
    contract_number TEXT NOT NULL,             -- e.g. "GOV-2013-041", "PVT-2013-012"
    name TEXT NOT NULL,                        -- e.g. "Puente Nacional Highway Extension"
    description TEXT,                          -- Brief description of the project

    -- Type: GOVERNMENT or PRIVATE
    contract_type TEXT NOT NULL CHECK (contract_type IN ('GOVERNMENT', 'PRIVATE')),

    -- Issuer
    issuer_name TEXT NOT NULL,                 -- e.g. "Ministry of Infrastructure", "Meridian Holdings Ltd."
    issuer_faction_id UUID REFERENCES factions(id) ON DELETE SET NULL,  -- NULL for government contracts
    issuer_nation_id UUID NOT NULL REFERENCES nations(id),

    -- Requirements
    required_sector TEXT NOT NULL DEFAULT 'Construction',
    required_subsector TEXT,                   -- e.g. "Civil Construction", "Industrial Construction", "Megaprojects"
    spec_category TEXT NOT NULL CHECK (spec_category IN ('Light Infrastructure', 'Heavy Infrastructure', 'Megaproject')),

    -- Financials
    budget BIGINT NOT NULL,                    -- Total budget in dollars
    timeline_months INTEGER NOT NULL,          -- Duration in months

    -- Classification tags
    project_type TEXT,                         -- e.g. "Civil Engineering", "Industrial"
    project_subtype TEXT,                      -- e.g. "School", "Highway", "Water Treatment"
    region TEXT,                               -- e.g. "Southern Corridor"

    -- Permits (JSONB array of { name, status: "required"|"approved" })
    permits_required JSONB DEFAULT '[]'::jsonb,

    -- Equipment (JSONB array of { name, quantity })
    equipment_required JSONB DEFAULT '[]'::jsonb,

    -- Materials (JSONB array of { name, quantity })
    materials_estimated JSONB DEFAULT '[]'::jsonb,

    -- Blueprint SVG (stored as text, rendered inline)
    blueprint_svg TEXT,

    -- Lifecycle
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'awarded', 'active', 'completed', 'failed', 'cancelled')),
    winner_faction_id UUID REFERENCES factions(id) ON DELETE SET NULL,
    awarded_at TIMESTAMPTZ,

    -- Progress tracking (for active contracts)
    progress_months INTEGER NOT NULL DEFAULT 0,
    started_at_tick INTEGER,

    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at_tick INTEGER,
    expires_at_tick INTEGER,                   -- Contract bid window closes

    -- Drawing number for blueprints
    drawing_number TEXT                        -- e.g. "GOV-2013-044-A1"
);

-- Bids placed by corporations on open contracts
CREATE TABLE IF NOT EXISTS corp_contract_bids (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contract_id UUID NOT NULL REFERENCES corp_contracts(id) ON DELETE CASCADE,
    faction_id UUID NOT NULL REFERENCES factions(id) ON DELETE CASCADE,
    nation_id UUID NOT NULL REFERENCES nations(id),

    -- Bid costs 2 AP
    ap_spent INTEGER NOT NULL DEFAULT 2,

    bid_amount BIGINT,                         -- Optional: how much the corp is bidding
    bid_message TEXT,                          -- Optional: pitch / notes

    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected')),

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at_tick INTEGER,

    UNIQUE(contract_id, faction_id)            -- One bid per corp per contract
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_corp_contracts_status ON corp_contracts(status);
CREATE INDEX IF NOT EXISTS idx_corp_contracts_nation ON corp_contracts(issuer_nation_id);
CREATE INDEX IF NOT EXISTS idx_corp_contracts_spec ON corp_contracts(spec_category);
CREATE INDEX IF NOT EXISTS idx_corp_contract_bids_contract ON corp_contract_bids(contract_id);
CREATE INDEX IF NOT EXISTS idx_corp_contract_bids_faction ON corp_contract_bids(faction_id);

-- RLS
ALTER TABLE corp_contracts ENABLE ROW LEVEL SECURITY;
ALTER TABLE corp_contract_bids ENABLE ROW LEVEL SECURITY;

-- ── corp_contracts: read-only for clients, system writes only ──

-- All authenticated users can read open contracts
CREATE POLICY "Contracts are viewable by all authenticated users"
    ON corp_contracts FOR SELECT TO authenticated USING (true);

-- No INSERT/UPDATE/DELETE for authenticated — contracts are created and managed
-- by the tick processor (service_role) or admin tools only.
-- service_role bypasses RLS, so no explicit policy needed for it.

-- ── corp_contract_bids: players can insert their own, system manages status ──

-- Anyone can read bids (needed to show bid count, check if already bid)
CREATE POLICY "Bids are viewable by all authenticated users"
    ON corp_contract_bids FOR SELECT TO authenticated USING (true);

-- Corps can place bids on their own behalf
CREATE POLICY "Corps can place their own bids"
    ON corp_contract_bids FOR INSERT TO authenticated
    WITH CHECK (
        faction_id = auth.uid()
        OR EXISTS (
            SELECT 1 FROM factions
            WHERE id = faction_id AND linked_user_id = auth.uid()
        )
    );

-- Bid status updates (accept/reject) are done by the contract issuer.
-- For GOVERNMENT contracts, the issuer_faction_id is NULL so only service_role
-- (tick processor) can update. For PRIVATE contracts, the issuing corp can update.
CREATE POLICY "Contract issuer can update bid status"
    ON corp_contract_bids FOR UPDATE TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM corp_contracts c
            WHERE c.id = contract_id
              AND c.issuer_faction_id IS NOT NULL
              AND (
                  c.issuer_faction_id = auth.uid()
                  OR EXISTS (
                      SELECT 1 FROM factions
                      WHERE id = c.issuer_faction_id AND linked_user_id = auth.uid()
                  )
              )
        )
    );

-- No DELETE for bids — bids are permanent once placed

COMMENT ON TABLE corp_contracts IS 'Construction contracts from government ministries or private corps. System-managed, read-only for clients.';
COMMENT ON TABLE corp_contract_bids IS 'Bids placed by construction corps on open contracts. Costs 2 AP to bid. Status managed by contract issuer or system.';
