-- ════════════════════════════════════════════════════════════════════════════════
-- Migration: Construction Contracts System
-- Date: 2026-04-01
--
-- Tables for automated government construction contract generation,
-- player bidding, and project tracking.
-- ════════════════════════════════════════════════════════════════════════════════

-- Active/open contracts generated by governments
CREATE TABLE IF NOT EXISTS construction_contracts (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nation_id           UUID NOT NULL REFERENCES nations(id) ON DELETE CASCADE,

    -- Template reference
    template_key        TEXT NOT NULL,           -- e.g. 'national_hospital', 'sports_stadium'
    sector              TEXT NOT NULL,           -- 'civil_engineering', 'industrial', 'mega_project'

    -- Contract details (generated from template + randomization)
    name                TEXT NOT NULL,           -- e.g. 'San Maria Hospital'
    description         TEXT,
    budget_ceiling       BIGINT NOT NULL,         -- max budget in dollars
    timeline_ticks      INT NOT NULL,            -- construction duration in ticks

    -- Requirements (JSONB for flexibility)
    required_materials  JSONB NOT NULL DEFAULT '{}',  -- { concrete: 10, steel: 8, ... }
    required_equipment  JSONB NOT NULL DEFAULT '[]',  -- ['work_trucks', 'excavators', ...]
    required_workforce  JSONB NOT NULL DEFAULT '{}',  -- { general: 120, skilled: 30 }

    -- Lifecycle
    status              TEXT NOT NULL DEFAULT 'open', -- open, bidding, awarded, in_progress, completed, expired
    generated_at_tick   INT NOT NULL,
    bidding_ends_tick   INT,                          -- tick when bidding closes
    awarded_to_faction  UUID REFERENCES factions(id) ON DELETE SET NULL,
    awarded_at_tick     INT,
    completed_at_tick   INT,

    -- Issuer info
    issuer_type         TEXT NOT NULL DEFAULT 'GOVERNMENT', -- GOVERNMENT or PRIVATE
    issuer_name         TEXT,                               -- e.g. 'Ministry of Infrastructure'

    created_at          TIMESTAMPTZ DEFAULT now(),
    updated_at          TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cc_nation_status ON construction_contracts(nation_id, status);
CREATE INDEX IF NOT EXISTS idx_cc_status ON construction_contracts(status);

-- Player bids on contracts
CREATE TABLE IF NOT EXISTS contract_bids (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contract_id         UUID NOT NULL REFERENCES construction_contracts(id) ON DELETE CASCADE,
    faction_id          UUID NOT NULL REFERENCES factions(id) ON DELETE CASCADE,

    bid_price           BIGINT NOT NULL,         -- total bid in dollars
    material_grades     JSONB NOT NULL DEFAULT '{}',  -- { concrete: 'STANDARD', steel: 'HIGH', ... }
    labor_count         INT NOT NULL DEFAULT 120,
    markup_pct          NUMERIC(5,2) NOT NULL DEFAULT 15,
    estimated_cost      BIGINT NOT NULL,
    estimated_quality   INT NOT NULL DEFAULT 65,  -- 0-100

    status              TEXT NOT NULL DEFAULT 'pending', -- pending, won, lost
    submitted_at_tick   INT NOT NULL,

    created_at          TIMESTAMPTZ DEFAULT now(),

    UNIQUE(contract_id, faction_id) -- one bid per faction per contract
);

CREATE INDEX IF NOT EXISTS idx_cb_contract ON contract_bids(contract_id);
CREATE INDEX IF NOT EXISTS idx_cb_faction ON contract_bids(faction_id);

-- Mega project cooldown tracker (per nation)
CREATE TABLE IF NOT EXISTS mega_project_cooldowns (
    nation_id           UUID PRIMARY KEY REFERENCES nations(id) ON DELETE CASCADE,
    last_completed_tick INT NOT NULL DEFAULT 0,
    cooldown_until_tick INT NOT NULL DEFAULT 0
);
