-- ═══════════════════════════════════════════════════════════════════════════════
-- SECTORS PHASE 0 — schema, defaults seed, admin-editable per-nation sectors
-- ═══════════════════════════════════════════════════════════════════════════════
-- Purpose:
--   Establishes the per-nation `sectors` table and the `faction_sector_popularity`
--   relation that will eventually replace ideology / momentum / gov_approval as
--   the driver of elections, bill effects, and cascade stats.
--
--   Phase 0 is INVISIBLE TO GAMEPLAY. No game logic reads these tables yet.
--   The admin Sectors tab uses them; everything else is unaffected.
--
-- Conventions:
--   * `sectors.popularity` is conceptually 0.0–10.0 in 0.1 increments.
--     Stored on `faction_sector_popularity.popularity` as integer tenths
--     (0–100). Display as one decimal place.
--   * `sectors.weight` is 1, 2, or 3 (national importance multiplier).
--   * `sectors.base_turnout` is 0.50–1.30 (voting participation multiplier).
--   * Defaults (`is_default = true`) can be renamed/reweighted but never deleted.
--   * Soft-delete via `is_active = false`; preserves popularity history.
--   * `sector_key` is auto-generated by the admin UI from `name` on insert,
--     then locked. Bills will reference sectors by key, not by name.
--
-- Triggers:
--   * After INSERT on nations -> seed_default_sectors(NEW.id)
--   * After INSERT on sectors -> backfill popularity = 0 for all factions in nation
--   * After INSERT on factions -> backfill popularity = 0 for all active sectors
--   * Before UPDATE on either -> refresh updated_at
--
-- All trigger functions are SECURITY DEFINER so they can bypass RLS during
-- normal user-initiated INSERTs.
--
-- Removable:
--   DROP TRIGGER ... ON nations/factions/sectors/faction_sector_popularity;
--   DROP FUNCTION seed_default_sectors, trg_seed_sectors_on_nation_insert,
--     trg_backfill_sector_popularity, trg_backfill_faction_popularity,
--     trg_sectors_set_updated_at;
--   DROP TABLE faction_sector_popularity, sectors;
-- ═══════════════════════════════════════════════════════════════════════════════

BEGIN;

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. TABLES
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS sectors (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    nation_id       uuid NOT NULL REFERENCES nations(id) ON DELETE CASCADE,
    sector_key      text NOT NULL,
    name            text NOT NULL,
    description     text NOT NULL DEFAULT '',
    weight          smallint NOT NULL DEFAULT 1
                        CHECK (weight BETWEEN 1 AND 3),
    base_turnout    numeric(3,2) NOT NULL DEFAULT 1.00
                        CHECK (base_turnout BETWEEN 0.50 AND 1.30),
    is_default      boolean NOT NULL DEFAULT false,
    is_active       boolean NOT NULL DEFAULT true,
    display_order   smallint NOT NULL DEFAULT 0,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (nation_id, sector_key)
);

CREATE INDEX IF NOT EXISTS idx_sectors_nation_active
    ON sectors (nation_id, is_active);

COMMENT ON TABLE sectors IS
    'Per-nation voter sectors. Populated with 12 defaults on nation creation; admins can add custom sectors via the admin panel.';
COMMENT ON COLUMN sectors.sector_key IS
    'Stable identifier (uppercase, underscored). Bills reference sectors by this key, never by name. Locked after insert.';
COMMENT ON COLUMN sectors.weight IS
    'National importance multiplier 1-3. Used in Total Weighted Popularity = popularity * weight * base_turnout.';
COMMENT ON COLUMN sectors.base_turnout IS
    'Voting participation multiplier 0.50-1.30. Default 1.00.';
COMMENT ON COLUMN sectors.is_active IS
    'Soft-delete flag. Inactive sectors retain their popularity rows for history but are excluded from gameplay calculations.';

CREATE TABLE IF NOT EXISTS faction_sector_popularity (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    faction_id  uuid NOT NULL REFERENCES factions(id) ON DELETE CASCADE,
    sector_id   uuid NOT NULL REFERENCES sectors(id) ON DELETE CASCADE,
    popularity  smallint NOT NULL DEFAULT 0
                    CHECK (popularity BETWEEN 0 AND 100),
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    UNIQUE (faction_id, sector_id)
);

CREATE INDEX IF NOT EXISTS idx_fsp_faction ON faction_sector_popularity (faction_id);
CREATE INDEX IF NOT EXISTS idx_fsp_sector  ON faction_sector_popularity (sector_id);

COMMENT ON TABLE faction_sector_popularity IS
    'Each faction''s popularity in each sector of its nation, stored as integer tenths (0-100 = 0.0-10.0).';
COMMENT ON COLUMN faction_sector_popularity.popularity IS
    'Integer tenths: 73 means 7.3 displayed popularity. Range 0-100.';

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. SEED FUNCTION — insert the 12 default sectors for one nation
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION seed_default_sectors(p_nation_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    INSERT INTO sectors (nation_id, sector_key, name, description, weight, base_turnout, is_default, is_active, display_order)
    VALUES
        (p_nation_id, 'RETIREES_PENSIONERS',           'Retirees & Pensioners',                                    '', 1, 1.00, true, true,  1),
        (p_nation_id, 'RELIGIOUS_CONSERVATIVES',       'Religious Conservatives',                                  '', 1, 1.00, true, true,  2),
        (p_nation_id, 'SERVICE_GIG_WORKERS',           'Service & Gig Workers',                                    '', 1, 1.00, true, true,  3),
        (p_nation_id, 'URBAN_PROFESSIONALS',           'Urban Professionals',                                      '', 1, 1.00, true, true,  4),
        (p_nation_id, 'SKILLED_TRADES_MANUFACTURING',  'Skilled Trades & Manufacturing',                           '', 1, 1.00, true, true,  5),
        (p_nation_id, 'RURAL_AGRICULTURAL',            'Rural & Agricultural',                                     '', 1, 1.00, true, true,  6),
        (p_nation_id, 'IMMIGRANT_MINORITY_COMMUNITIES','Immigrant & Minority Communities',                         '', 1, 1.00, true, true,  7),
        (p_nation_id, 'STUDENTS_YOUNG_PRECARIAT',      'Students & Young Precariat',                               '', 1, 1.00, true, true,  8),
        (p_nation_id, 'SMALL_BUSINESS_OWNERS',         'Small Business Owners',                                    '', 1, 1.00, true, true,  9),
        (p_nation_id, 'CAPITAL_OWNERS_EXECUTIVES',     'Capital Owners / Executives',                              '', 1, 1.00, true, true, 10),
        (p_nation_id, 'TECH_ENGINEERING_CLASS',        'Tech & Engineering Class',                                 '', 1, 1.00, true, true, 11),
        (p_nation_id, 'CULTURAL_PRODUCERS',            'Cultural Producers (media, academia, arts, nonprofits)',   '', 1, 1.00, true, true, 12)
    ON CONFLICT (nation_id, sector_key) DO NOTHING;
END;
$$;

COMMENT ON FUNCTION seed_default_sectors(uuid) IS
    'Inserts the 12 default sectors for the given nation. Idempotent; safe to call multiple times.';

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. TRIGGERS
-- ─────────────────────────────────────────────────────────────────────────────

-- 3a. New nation -> seed 12 default sectors
CREATE OR REPLACE FUNCTION trg_seed_sectors_on_nation_insert()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    PERFORM seed_default_sectors(NEW.id);
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS seed_sectors_on_nation_insert ON nations;
CREATE TRIGGER seed_sectors_on_nation_insert
    AFTER INSERT ON nations
    FOR EACH ROW EXECUTE FUNCTION trg_seed_sectors_on_nation_insert();

-- 3b. New sector -> backfill popularity = 0 for every faction in that nation
CREATE OR REPLACE FUNCTION trg_backfill_sector_popularity()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    INSERT INTO faction_sector_popularity (faction_id, sector_id, popularity)
    SELECT f.id, NEW.id, 0
    FROM factions f
    WHERE f.nation_id = NEW.nation_id
    ON CONFLICT (faction_id, sector_id) DO NOTHING;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS backfill_sector_popularity ON sectors;
CREATE TRIGGER backfill_sector_popularity
    AFTER INSERT ON sectors
    FOR EACH ROW EXECUTE FUNCTION trg_backfill_sector_popularity();

-- 3c. New faction -> backfill popularity = 0 for every active sector in its nation
CREATE OR REPLACE FUNCTION trg_backfill_faction_popularity()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NEW.nation_id IS NULL THEN
        RETURN NEW;
    END IF;

    INSERT INTO faction_sector_popularity (faction_id, sector_id, popularity)
    SELECT NEW.id, s.id, 0
    FROM sectors s
    WHERE s.nation_id = NEW.nation_id AND s.is_active = true
    ON CONFLICT (faction_id, sector_id) DO NOTHING;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS backfill_faction_popularity ON factions;
CREATE TRIGGER backfill_faction_popularity
    AFTER INSERT ON factions
    FOR EACH ROW EXECUTE FUNCTION trg_backfill_faction_popularity();

-- 3d. updated_at maintenance for both tables
CREATE OR REPLACE FUNCTION trg_sectors_set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS sectors_set_updated_at ON sectors;
CREATE TRIGGER sectors_set_updated_at
    BEFORE UPDATE ON sectors
    FOR EACH ROW EXECUTE FUNCTION trg_sectors_set_updated_at();

DROP TRIGGER IF EXISTS fsp_set_updated_at ON faction_sector_popularity;
CREATE TRIGGER fsp_set_updated_at
    BEFORE UPDATE ON faction_sector_popularity
    FOR EACH ROW EXECUTE FUNCTION trg_sectors_set_updated_at();

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. RLS POLICIES — public read, admin-only write
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE sectors ENABLE ROW LEVEL SECURITY;
ALTER TABLE faction_sector_popularity ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow select for all" ON sectors;
CREATE POLICY "Allow select for all" ON sectors
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin writes" ON sectors;
CREATE POLICY "Admin writes" ON sectors
    FOR ALL TO authenticated
    USING (is_admin())
    WITH CHECK (is_admin());

DROP POLICY IF EXISTS "Allow select for all" ON faction_sector_popularity;
CREATE POLICY "Allow select for all" ON faction_sector_popularity
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin writes" ON faction_sector_popularity;
CREATE POLICY "Admin writes" ON faction_sector_popularity
    FOR ALL TO authenticated
    USING (is_admin())
    WITH CHECK (is_admin());

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. BACKFILL — seed defaults for every existing nation
-- ─────────────────────────────────────────────────────────────────────────────

DO $$
DECLARE
    n_id uuid;
BEGIN
    FOR n_id IN SELECT id FROM nations LOOP
        PERFORM seed_default_sectors(n_id);
    END LOOP;
END $$;

COMMIT;
