-- ════════════════════════════════════════════════════════════════════════════════
-- Health Insurance — Phase 4: Claim events + resolution RPC
--
-- Adds the moral-decision gameplay loop. Each corp tick, each operating pool
-- rolls for a claim event (probability scales with policyholder count,
-- severity scales with coverage tier). Players resolve pending claims via a
-- modal on the Operations page by calling resolve_health_insurance_claim,
-- which mutates reputation + cash and records whether a lawsuit was rolled
-- (Phase 5 will process the lawsuit roll into actual damages).
--
-- Only one pending claim per pool at a time — the claim generator checks
-- this first. Players have to resolve before another fires.
--
-- Idempotent. Safe to re-run.
-- ════════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS health_insurance_claims (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pool_id             UUID NOT NULL REFERENCES health_insurance_pools(id) ON DELETE CASCADE,
    faction_id          UUID NOT NULL REFERENCES factions(id) ON DELETE CASCADE,
    nation_id           UUID NOT NULL REFERENCES nations(id) ON DELETE CASCADE,

    -- Claim content
    claim_amount        BIGINT NOT NULL,
    citizen_name        TEXT NOT NULL,
    citizen_age         INT NOT NULL,
    condition_key       TEXT NOT NULL,          -- short label, e.g. 'emergency_surgery'
    flavor_blurb        TEXT NOT NULL,          -- full narrative for the modal

    -- Lifecycle
    status              TEXT NOT NULL DEFAULT 'pending',
    fired_at_tick       INT NOT NULL,
    resolved_at_tick    INT,

    -- Resolution deltas (populated at resolution time — useful for audit + event log)
    cash_delta          BIGINT NOT NULL DEFAULT 0,
    reputation_delta    INT NOT NULL DEFAULT 0,
    lawsuit_pending     BOOLEAN NOT NULL DEFAULT false,

    created_at          TIMESTAMPTZ DEFAULT NOW()
);

DO $$ BEGIN
    ALTER TABLE health_insurance_claims
        ADD CONSTRAINT health_insurance_claims_status_check
        CHECK (status IN ('pending', 'pay', 'deny', 'negotiate', 'expired'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- One pending claim per pool at any time. The tick processor uses this to
-- skip claim generation when a claim is already awaiting resolution.
CREATE UNIQUE INDEX IF NOT EXISTS idx_health_insurance_claims_one_pending_per_pool
    ON health_insurance_claims (pool_id)
    WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS idx_health_insurance_claims_faction_pending
    ON health_insurance_claims (faction_id)
    WHERE status = 'pending';

COMMENT ON TABLE health_insurance_claims IS
    'Per-pool claim events generated by the corp tick processor. One pending row per pool at a time; resolved by players via resolve_health_insurance_claim RPC.';

-- ────────────────────────────────────────────────────────────────────────────────
-- RLS — same pattern as health_insurance_pools: SELECT-only from client. Writes
-- go through the edge function (service role, bypasses RLS) for generation
-- and through the RPC (SECURITY DEFINER) for resolution.
-- ────────────────────────────────────────────────────────────────────────────────
ALTER TABLE health_insurance_claims ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    CREATE POLICY "Anyone can read health_insurance_claims"
        ON health_insurance_claims
        FOR SELECT
        USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ════════════════════════════════════════════════════════════════════════════════
-- RPC: resolve_health_insurance_claim
--
-- Applies a pay/deny/negotiate decision: updates corp_cash_reserves and
-- corp_reputation, records the deltas on the claim row, rolls for a lawsuit
-- on deny/negotiate, and transitions status from 'pending' to the decision.
--
-- Lawsuit roll lives here (not in Phase 5) so the probability is pinned at
-- the moment of the decision — if rep drifts afterward, the roll doesn't
-- retroactively change. Phase 5 reads lawsuit_pending=true rows and fires
-- the actual damages event.
-- ════════════════════════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION resolve_health_insurance_claim(
    p_claim_id UUID,
    p_decision TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_user_id          UUID;
    v_claim            health_insurance_claims%ROWTYPE;
    v_faction          factions%ROWTYPE;
    v_current_tick     INT;
    v_cash_delta       BIGINT := 0;
    v_rep_delta        INT := 0;
    v_new_cash         BIGINT;
    v_new_rep          INT;
    v_lawsuit_pending  BOOLEAN := false;
    v_lawsuit_chance   NUMERIC;
BEGIN
    -- ── Auth ──
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Not authenticated';
    END IF;

    -- ── Decision validation ──
    IF p_decision NOT IN ('pay', 'deny', 'negotiate') THEN
        RAISE EXCEPTION 'Invalid decision: %. Must be pay/deny/negotiate.', p_decision;
    END IF;

    -- ── Lock the claim. FOR UPDATE prevents two concurrent clicks from both
    --    reducing cash twice. The WHERE clause filters out already-resolved
    --    rows so a double-fire just returns a "not found" error instead of
    --    silently re-applying the decision. ──
    SELECT * INTO v_claim
    FROM health_insurance_claims
    WHERE id = p_claim_id
      AND status = 'pending'
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Claim not found or already resolved';
    END IF;

    -- ── Ownership gate (same pattern as set_health_insurance_tiers) ──
    SELECT * INTO v_faction FROM factions WHERE id = v_claim.faction_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Faction not found';
    END IF;
    IF v_faction.id <> v_user_id
       AND COALESCE(v_faction.linked_user_id, '00000000-0000-0000-0000-000000000000'::uuid) <> v_user_id THEN
        RAISE EXCEPTION 'You do not own this faction';
    END IF;

    -- ── Current tick for stamping ──
    SELECT COALESCE(current_tick, 0) INTO v_current_tick
    FROM shard WHERE name = 'Alpha Shard';

    -- ── Compute deltas + lawsuit roll per decision ──
    -- Lawsuit probability uses reputation AT THIS MOMENT (not at claim fire
    -- time) so a player who lets rep rot between claim and decision gets the
    -- worse odds, and vice versa.
    v_lawsuit_chance := GREATEST(0, (100 - COALESCE(v_faction.corp_reputation, 65))) / 200.0;

    IF p_decision = 'pay' THEN
        v_cash_delta := -v_claim.claim_amount;
        v_rep_delta  := 1;
    ELSIF p_decision = 'negotiate' THEN
        v_cash_delta := -CEIL(v_claim.claim_amount / 2.0);
        v_rep_delta  := 0;
        -- Negotiate is half the deny lawsuit chance — partial payment buys
        -- goodwill that makes a lawsuit much less likely.
        IF random() < v_lawsuit_chance / 2.0 THEN
            v_lawsuit_pending := true;
        END IF;
    ELSE -- deny
        v_cash_delta := 0;
        v_rep_delta  := -3;
        IF random() < v_lawsuit_chance THEN
            v_lawsuit_pending := true;
        END IF;
    END IF;

    -- ── Apply cash + reputation ──
    v_new_cash := COALESCE(v_faction.corp_cash_reserves, 0) + v_cash_delta;
    v_new_rep  := GREATEST(0, LEAST(100, COALESCE(v_faction.corp_reputation, 65) + v_rep_delta));

    UPDATE factions
       SET corp_cash_reserves = v_new_cash,
           corp_reputation    = v_new_rep
     WHERE id = v_faction.id;

    -- ── Resolve the claim ──
    UPDATE health_insurance_claims
       SET status           = p_decision,
           resolved_at_tick = v_current_tick,
           cash_delta       = v_cash_delta,
           reputation_delta = v_rep_delta,
           lawsuit_pending  = v_lawsuit_pending
     WHERE id = p_claim_id;

    RETURN jsonb_build_object(
        'success',          true,
        'decision',         p_decision,
        'cash_delta',       v_cash_delta,
        'reputation_delta', v_rep_delta,
        'new_reputation',   v_new_rep,
        'lawsuit_pending',  v_lawsuit_pending
    );
END;
$$;

GRANT EXECUTE ON FUNCTION resolve_health_insurance_claim(UUID, TEXT) TO authenticated;

-- ════════════════════════════════════════════════════════════════════════════════
-- VERIFY
-- ════════════════════════════════════════════════════════════════════════════════
SELECT 'health_insurance_claims' AS table_name, COUNT(*) AS rows
  FROM health_insurance_claims;

SELECT proname, pg_get_function_arguments(oid) AS args
  FROM pg_proc
 WHERE proname = 'resolve_health_insurance_claim';
