/**
 * shipping.js — Shipping route mechanics + helpers
 *
 * Generation hooks (generateShippingRoutes, generateOrganicRoutes) were
 * stubbed in Phase 10A when the goods-trade engine was wiped. The
 * stateless helpers below (sector→subsector mapping, revenue ceiling
 * math, demand-level bands) remain in active use by corp-operations
 * shipping UIs and existing shipping_routes rows.
 */

// ==================== SHIPPING SECTOR MAPPING ====================

/**
 * Maps trade sectors to shipping subsectors and cargo metadata.
 * Determines which shipping corps can serve which trade routes.
 */
// KNOWN ISSUE — three-way duplication. The canonical sector→subsector map
// also lives, verbatim, in:
//   - supabase/functions/advance-corp-tick/index.ts (inline copy near
//     "SHIPPING ROUTE GENERATION")
//   - the sector_meta CTE inside the generate_organic_shipping_routes
//     SQL RPC (latest:
//     20260429_organic_routes_fuel_energy_specialized_transport.sql)
// Any change to a row here must be replicated in BOTH of those copies in
// the same commit, or routes generated by one path will disagree with
// the others. A future refactor should collapse to one source — flagged
// for follow-up, not urgent.
export var SHIPPING_SECTOR_MAP = {
    fuel_energy:        { subsector: 'specialized_transport', category: 'FUEL',     goods: 'Fuel & Energy Products',   goodsSub: 'Petroleum, LNG, coal, refined fuels',        vessel: 'Tanker',          vesselNote: 'Double-hull required for petroleum. Hazmat protocols for LNG.', unit: 'tons' },
    minerals:           { subsector: 'bulk_cargo',           category: 'MINERALS', goods: 'Minerals & Raw Materials', goodsSub: 'Iron ore, copper, bauxite, rare earths',      vessel: 'Bulk Carrier',    vesselNote: 'Heavy-load bulk. No special requirements.',                    unit: 'tons' },
    grains_staples:     { subsector: 'bulk_cargo',           category: 'FOOD',     goods: 'Grains & Staples',         goodsSub: 'Wheat, rice, corn, soybeans, cooking oils',   vessel: 'Bulk Carrier',    vesselNote: 'Dry bulk holds. Moisture control required.',                   unit: 'tons' },
    livestock_dairy:    { subsector: 'bulk_cargo',           category: 'FOOD',     goods: 'Livestock & Dairy',        goodsSub: 'Feed crops, processed dairy, frozen meat',    vessel: 'Bulk Carrier',    vesselNote: 'Temperature-controlled holds for dairy products.',             unit: 'tons' },
    cash_crops:         { subsector: 'bulk_cargo',           category: 'FOOD',     goods: 'Cash Crops',               goodsSub: 'Coffee, cocoa, tobacco, cotton, rubber',      vessel: 'Bulk Carrier',    vesselNote: 'Standard dry bulk. Humidity control for coffee/cocoa.',        unit: 'tons' },
    manufactured_goods: { subsector: 'container_freight',    category: 'MFG',      goods: 'Manufactured Goods',       goodsSub: 'Consumer goods, vehicles, industrial parts',  vessel: 'Container Ship',  vesselNote: 'Standard container ops. Crane-equipped ports required.',       unit: 'TEU' },
    technology:         { subsector: 'container_freight',    category: 'TECH',     goods: 'Technology & Electronics',  goodsSub: 'Semiconductors, electronics, precision equipment', vessel: 'Container Ship', vesselNote: 'Climate-controlled containers. High insurance requirement.', unit: 'TEU' },
    fruits_vegetables:  { subsector: 'container_freight',    category: 'FOOD',     goods: 'Perishable Produce',       goodsSub: 'Fresh fruit, vegetables, seafood, aquaculture', vessel: 'Reefer Ship',   vesselNote: 'Refrigerated holds required. Cold chain critical.',            unit: 'tons' },
    arms:               { subsector: 'specialized_transport', category: 'ARMS',    goods: 'Arms & Military Equipment', goodsSub: 'Vehicles, munitions, defense systems',       vessel: 'Military Transport', vesselNote: 'Security clearance required. Armed escort may be assigned.', unit: 'tons' },
};

/**
 * Minimum bilateral trade volume (dollars) to generate a shipping route.
 * Below this threshold, the volume is too small to justify a dedicated route.
 */
export var SHIPPING_ROUTE_THRESHOLD = 50000000; // $50M

/**
 * Annual revenue fraction — shipping corps earn this share of the trade value
 * they move, expressed as an ANNUAL rate. Per-transit revenue divides by
 * MONTHS_PER_YEAR so the corp earns the monthly slice of that annual total
 * per completed trip, regardless of how many trips a route can fit per year.
 *
 * Bulk cargo: lower margin. Container freight: medium. Specialized: highest.
 */
export var SHIPPING_REVENUE_RATES = {
    bulk_cargo: 0.010,            // 1.0% of annual trade value
    container_freight: 0.012,     // 1.2% of annual trade value
    specialized_transport: 0.016, // 1.6% of annual trade value
};

/** Ticks per year — used to turn the annual rate into a per-trip payout. */
export var MONTHS_PER_YEAR = 12;

/**
 * Service-rate band. Floor is flat so small lanes still have enough margin
 * to cover fuel + a coastal-class ship. Ceiling scales with the lane's
 * trade volume (capped at HARD_CEILING_PER_TRIP) so $6B+ lanes can actually
 * pay for the Container/Tanker ships they demand — a flat $750k ceiling
 * used to leave every big lane unprofitable against fleet maintenance.
 * MIN_CEILING_PER_TRIP preserves the pre-scaling $750k as a soft floor on
 * the ceiling so small lanes see the familiar "$250k–$750k" band.
 */
export var MIN_REVENUE_PER_TRIP = 250000;
export var MIN_CEILING_PER_TRIP = 750000;
export var HARD_CEILING_PER_TRIP = 5000000;

/**
 * Compute the per-trip revenue ceiling for a specific route. The uncapped
 * target is tradeVolume × subsector_rate / 12 (i.e. the monthly slice of the
 * annual revenue share). We floor that at MIN_CEILING_PER_TRIP so small
 * lanes still have a $750k ceiling to aim at, and cap it at
 * HARD_CEILING_PER_TRIP so $15B mega-lanes don't uncork runaway rates.
 */
export function computeServiceRateCeiling(tradeVolume, subsector) {
    var rate = SHIPPING_REVENUE_RATES[subsector] || SHIPPING_REVENUE_RATES.bulk_cargo;
    var uncapped = (Number(tradeVolume) || 0) * rate / MONTHS_PER_YEAR;
    return Math.round(Math.min(HARD_CEILING_PER_TRIP, Math.max(MIN_CEILING_PER_TRIP, uncapped)));
}

/**
 * Clamp a candidate per-trip revenue into the service-rate band for a route.
 * Ceiling may be passed directly (e.g. from computeServiceRateCeiling) or
 * defaults to MIN_CEILING_PER_TRIP for callers that don't know the lane.
 */
export function clampServiceRate(value, ceiling) {
    var v = Number(value) || 0;
    var top = Number(ceiling) || MIN_CEILING_PER_TRIP;
    if (top < MIN_CEILING_PER_TRIP) top = MIN_CEILING_PER_TRIP;
    if (top > HARD_CEILING_PER_TRIP) top = HARD_CEILING_PER_TRIP;
    if (v <= 0) return MIN_REVENUE_PER_TRIP;
    return Math.round(Math.min(top, Math.max(MIN_REVENUE_PER_TRIP, v)));
}

/**
 * Tier multipliers — applied post-bid when the shipping claim is created.
 * Agreement-backed lanes get a bonus (formal bilateral trade = higher stakes
 * for both nations). Organic lanes are neutral here (1.0); their discount is
 * applied pre-bid during route generation via ORGANIC_REVENUE_MULTIPLIER.
 */
export var AGREEMENT_REVENUE_MULTIPLIER = 1.2;
export var ORGANIC_REVENUE_MULTIPLIER_POST = 1.0; // post-bid: no extra organic penalty; pre-bid 0.35 handles discount

export function revenueTierMultiplier(route) {
    // post-bid: agreement lanes get a bonus; organic lanes keep the clamped bid unchanged.
    return route && route.trade_agreement_id ? AGREEMENT_REVENUE_MULTIPLIER : ORGANIC_REVENUE_MULTIPLIER_POST;
}

/**
 * Canonical transit-tick formula. Always returns >= 1 so transit_ticks
 * is never zero on a freshly-written route. Codifies what the runtime
 * fallbacks (`|| 2`) used to produce, letting the fallbacks be stripped.
 * Mirrored verbatim by _shipTransitTicks in
 * supabase/functions/advance-corp-tick/index.ts and the inline literal
 * in generate_organic_shipping_routes — keep all three in sync.
 * @param {number} proximity - 0 (bordering) to 100 (far)
 * @returns {number} transit ticks (1 for prox >= 71, 2 otherwise)
 */
export function calculateTransitTicks(proximity) {
    var p = Number(proximity) || 0;
    return p >= 71 ? 1 : 2;
}

/**
 * Determine demand level from trade volume relative to threshold.
 * @param {number} volume - bilateral trade volume in dollars
 * @returns {string} CRITICAL, HIGH, MODERATE, or LOW
 */
export function getDemandLevel(volume) {
    if (volume >= 500000000) return 'CRITICAL';
    if (volume >= 200000000) return 'HIGH';
    if (volume >= 100000000) return 'MODERATE';
    return 'LOW';
}

/**
 * Determine route scope based on proximity and whether it's a government contract.
 * @param {number} proximity - 0 (bordering) to 100 (far)
 * @param {boolean} isGovContract - true for government/military routes
 * @returns {string} COASTAL, INTERNATIONAL, or GOVERNMENT
 */
export function getRouteScope(proximity, isGovContract) {
    if (isGovContract) return 'GOVERNMENT';
    return proximity <= 15 ? 'COASTAL' : 'INTERNATIONAL';
}

/**
 * Phase 10A stub. The original generator depended on the trade_partners
 * table (now dropped) and the goods-trade engine (now wiped). Restore
 * with a real implementation when the goods rebuild lands.
 */
export async function generateShippingRoutes(_supabase, _currentTick) {
    // Phase 10A: trade_partners table dropped. Route generation
    // depends on the goods-trade engine which was wiped. Existing
    // shipping_routes rows stay viewable; no new routes are generated
    // until the goods rebuild lands.
    return { generated: 0, expired: 0, total: 0 };
}

// ==================== ORGANIC TRADE ROUTES ====================

/**
 * Revenue multiplier for organic routes vs agreement-backed routes.
 * Organic routes pay less to incentivize real trade deals.
 */
var ORGANIC_REVENUE_MULTIPLIER = 0.35; // pre-bid: organic routes are generated at 35% of normal lane economics

/**
 * Minimum proximity to generate organic routes between nations.
 * Nations further apart than this don't have enough natural commerce.
 * Proximity cap removed (third pass). The TS generator in
 * advance-corp-tick/index.ts no longer gates on proximity — only on a
 * $5B volume floor. This constant is retained at 99 so any legacy client
 * consumer still gets a permissive upper bound rather than undefined.
 */
var ORGANIC_MIN_PROXIMITY = 99; // effectively unlimited — volume floor is the real gate

/**
 * Max organic routes per nation pair per tick.
 * One per pair so each near-neighbor spot-market lane is distinct, not
 * duplicated two-ways with two cargo picks.
 */
var ORGANIC_MAX_ROUTES_PER_PAIR = 1;

/**
 * Organic route expiry in ticks. Routes regenerate with potentially different goods.
 */
var ORGANIC_ROUTE_LIFETIME = 8;

/**
 * Sectors eligible for organic trade (excludes arms — those need government contracts).
 */
var ORGANIC_ELIGIBLE_SECTORS = [
    'fuel_energy', 'minerals', 'grains_staples', 'livestock_dairy',
    'cash_crops', 'manufactured_goods', 'technology', 'fruits_vegetables'
];

/**
 * Generate organic trade routes — baseline commerce between neighboring nations.
 * These exist regardless of trade agreements, representing natural free-market trade.
 * Lower volume and revenue than agreement-backed routes.
 *
 * @param {Object} supabase    - Supabase client (service_role)
 * @param {number} currentTick - current game tick
 * @returns {Object} { generated, expired }
 */
export async function generateOrganicRoutes(_supabase, _currentTick) {
    // Phase 10A: organic-routes generator read manufacturing_output
    // and tariffs (both dropped in Phase 9) and depended on the
    // goods-trade engine. No new routes generated until the rebuild.
    return { generated: 0, expired: 0 };
}
