-- Add per-ideology-tag approval modifiers to factions.
-- Stores bonuses/penalties like {"LIBERTY": 5, "NATIONALISM": -3}.
-- Used in elections: effective_approval = base_approval + avg(matching tag modifiers).
-- Generated by bill enactment; decays 1 point/tick toward 0.

ALTER TABLE factions
ADD COLUMN IF NOT EXISTS ideology_modifiers JSONB DEFAULT '{}'::JSONB;
